# NumPy and Pandas Assignment


In [3]:
!pip install pandas


   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.6 MB 1.9 MB/s eta 0:00:07
   ---------------------------------------- 0.0/11.6 MB 1.9 MB/s eta 0:00:07
   ---------------------------------------- 0.1/11.6 MB 327.7 kB/s eta 0:00:36
   ---------------------------------------- 0.1/11.6 MB 587.0 kB/s eta 0:00:20
   ---------------------------------------- 0.1/11.6 MB 587.0 kB/s eta 0:00:20
   ---------------------------------------- 0.1/11.6 MB 450.6 kB/s eta 0:00:26
    --------------------------------------- 0.2/11.6 MB 758.5 kB/s eta 0:00:16
    --------------------------------------- 0.2/11.6 MB 758.5 kB/s eta 0:00:16
   - -------------------------------------- 0.4/11.6 MB 880.6 kB/s eta 0:00:13
   - -------------------------------------- 0.5/11.6 MB 1.1 MB/s eta 0:00:11
   - -------------------------------------- 0.5/11.6 MB 1.1 MB/s eta 0:00:11
   -- ------------------------------------- 0.7/11.6 MB 1.4 MB/s eta 


[notice] A new release of pip is available: 24.0 -> 24.1
[notice] To update, run: C:\Users\DELL\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [2]:
import numpy as np
import pandas as pd

In [2]:
# Task 1: NumPy Basics

# 1. Array Creation
# Create a 1D and a 2D NumPy array
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr_1d)

1D Array: [1 2 3 4 5]


In [5]:
arr_2d = np.array([[1, 2, 3,4], [4, 5, 6,7]])
print("2D Array:\n", arr_2d)


2D Array:
 [[1 2 3 4]
 [4 5 6 7]]


In [6]:
# 2. Array Operations
# Perform basic arithmetic operations on the arrays
arr_1d_add = arr_1d + 10
arr_2d_mult = arr_2d * 2
print("1D Array + 10:", arr_1d_add)
print("2D Array * 2:\n", arr_2d_mult)

1D Array + 10: [11 12 13 14 15]
2D Array * 2:
 [[ 2  4  6  8]
 [ 8 10 12 14]]


In [7]:
# 3. Indexing and Slicing
# Demonstrate indexing and slicing on the arrays
print("First element of 1D array:", arr_1d[0])
print("First row of 2D array:\n", arr_2d[0, :])

First element of 1D array: 1
First row of 2D array:
 [1 2 3 4]


In [9]:
# 4. Shape and Reshape
# Show how to check the shape of an array and reshape it
print("Shape of 2D array:", arr_2d.shape)
reshaped_arr = arr_2d.reshape((4, 2))
print("Reshaped 2D Array:\n", reshaped_arr)


Shape of 2D array: (2, 4)
Reshaped 2D Array:
 [[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [10]:
# Task 2: Pandas Basics

# 1. Series and DataFrame Creation
# Create a Pandas Series and DataFrame
s = pd.Series([1, 2, 3, 4, 5])
print("Pandas Series:\n", s)

Pandas Series:
 0    1
1    2
2    3
3    4
4    5
dtype: int64


In [6]:
df = pd.DataFrame({
    'A': [1, 2, 3,4],
    'B': [4, 5, 6,6],
    'C': [7, 8, 9,9],
    'D': [10, 11, 12,12]
})
print("Pandas DataFrame:\n", df)

Pandas DataFrame:
    A  B  C   D
0  1  4  7  10
1  2  5  8  11
2  3  6  9  12
3  4  6  9  12


In [3]:
# 2. Reading Data
# Read data from a CSV file (ensure you have a sample CSV file in your repository)
df_read = pd.read_csv('Titanic-Dataset.csv')
print("Read DataFrame from CSV:\n", df_read)

Read DataFrame from CSV:
      PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                         

In [5]:
# 3. Data Inspection
# Perform basic data inspection methods
print("Head of DataFrame:\n", df_read.head())
print("Info of DataFrame:\n", df_read.info())
print("Description of DataFrame:\n", df_read.describe())

Head of DataFrame:
    PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500

In [7]:
# 4. Data Manipulation
# Selecting Data
print("Column A:\n", df_read['Name'])
print("Columns A and B:\n", df_read[['Name', 'Sex']])

Column A:
 0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...                        
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object
Columns A and B:
                                                   Name     Sex
0                              Braund, Mr. Owen Harris    male
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female
2                               Heikkinen, Miss. Laina  female
3         Futrelle, Mrs. Jacques Heath (Lily May Peel

In [11]:
# Filtering Data
filtered_df = df_read[df_read['Age'] > 28]
print("Filtered DataFrame (A > 28):\n", filtered_df)

Filtered DataFrame (A > 28):
      PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
4              5         0       3   
6              7         0       1   
11            12         1       1   
..           ...       ...     ...   
873          874         0       3   
879          880         1       1   
881          882         0       3   
885          886         0       3   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
..                                     

In [12]:
# Adding/Removing Columns from DataFrame df
df['D'] = df['A'] + df['B']
print("DataFrame with new column D:\n", df)
df.drop('D', axis=1, inplace=True)
print("DataFrame after dropping column D:\n", df)

DataFrame with new column D:
    A  B  C   D
0  1  4  7   5
1  2  5  8   7
2  3  6  9   9
3  4  6  9  10
DataFrame after dropping column D:
    A  B  C
0  1  4  7
1  2  5  8
2  3  6  9
3  4  6  9


In [13]:
# Handling Missing Data
df_with_nan = df.copy()
df_with_nan.loc[1, 'B'] = np.nan
print("DataFrame with NaN:\n", df_with_nan)
print("DataFrame after dropping NaN:\n", df_with_nan.dropna())
print("DataFrame after filling NaN with 0:\n", df_with_nan.fillna(0))

DataFrame with NaN:
    A    B  C
0  1  4.0  7
1  2  NaN  8
2  3  6.0  9
3  4  6.0  9
DataFrame after dropping NaN:
    A    B  C
0  1  4.0  7
2  3  6.0  9
3  4  6.0  9
DataFrame after filling NaN with 0:
    A    B  C
0  1  4.0  7
1  2  0.0  8
2  3  6.0  9
3  4  6.0  9


In [14]:

# Handling Missing Data
df_with_nan = df.copy()
df_with_nan.loc[1, 'B'] = np.nan
print("DataFrame with NaN:\n", df_with_nan)
print("DataFrame after dropping NaN:\n", df_with_nan.dropna())
print("DataFrame after filling NaN with 0:\n", df_with_nan.fillna(0))

DataFrame with NaN:
    A    B  C
0  1  4.0  7
1  2  NaN  8
2  3  6.0  9
3  4  6.0  9
DataFrame after dropping NaN:
    A    B  C
0  1  4.0  7
2  3  6.0  9
3  4  6.0  9
DataFrame after filling NaN with 0:
    A    B  C
0  1  4.0  7
1  2  0.0  8
2  3  6.0  9
3  4  6.0  9


In [16]:
#Task 3: Data Analysis with Pandas
# Aggregations
print("Mean of column Age:", df_read['Age'].mean())
print("Sum of column Age:", df_read['Age'].sum())

Mean of column Age: 29.69911764705882
Sum of column Age: 21205.17


In [17]:
# Merging and Joining
df1 = pd.DataFrame({'key': ['A', 'B', 'C'], 'value': [1, 2, 3]})
df2 = pd.DataFrame({'key': ['A', 'B', 'D'], 'value': [4, 5, 6]})
merged_df = pd.merge(df1, df2, on='key', how='inner')
print("Merged DataFrame:\n", merged_df)

Merged DataFrame:
   key  value_x  value_y
0   A        1        4
1   B        2        5


In [18]:
# Pivot Tables
pivot_df = df.pivot_table(values='C', index='A', columns='B', aggfunc='mean')
print("Pivot Table:\n", pivot_df)

Pivot Table:
 B    4    5    6
A               
1  7.0  NaN  NaN
2  NaN  8.0  NaN
3  NaN  NaN  9.0
4  NaN  NaN  9.0


In [19]:
# Time Series Analysis
df['date'] = pd.date_range(start='1/1/2020', periods=len(df), freq='D')
df.set_index('date', inplace=True)
print("DataFrame with Date Index:\n", df)
resampled_df = df.resample('M').mean()
print("Resampled DataFrame:\n", resampled_df)

DataFrame with Date Index:
             A  B  C
date               
2020-01-01  1  4  7
2020-01-02  2  5  8
2020-01-03  3  6  9
2020-01-04  4  6  9
Resampled DataFrame:
               A     B     C
date                       
2020-01-31  2.5  5.25  8.25
